/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CutTbe(props) {
  const { nodes, materials } = useGLTF('/cutTube.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={6.011}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus_1.geometry}
          material={nodes.Torus_1.material}
          scale={0.5}
          rotation={[15, 20,90]}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus_2.geometry}
          material={nodes.Torus_2.material}
        /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/cutTube.glb')