/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Dimond(props) {
  const { nodes, materials } = useGLTF('/dimond.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        position={[-0.209, 1.938, 0.243]}
        scale={[1, 3, 2]}
      />
    </group>
  )
}

useGLTF.preload('/dimond.glb')
